Gym Management System/Models/VisitorTB.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorTB
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> visitDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public string enquiryMode { get; set; }
    }
}

Gym Management System/Controllers/DashboardController.cs
using Gym_Management_System.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Gym_Management_System.Controllers
{
    public class DashboardController : Controller
    {
        private SaveData objSaveData;
        private GYMDBEntities4 db = new GYMDBEntities4();
        public DashboardController()
        {
            objSaveData = new SaveData();
        }
        // GET: Dashboad
        public ActionResult Dues()
        {
            var transactions = db.TransactionTBs
    .Where(t => t.DueAmount != null && t.DueAmount != 0)
    .Include(t => t.MemberTB)
    .ToList();
            var memberModel = db.MemberTBs.ToList();
            ViewBag.Transactions = transactions;
            ViewBag.Members = memberModel;
            return View();
        }
        public ActionResult Payment()
        {
            IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
            var data = mDta.ToList();
            IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
            var tD = tData.ToList();
            ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
            ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
            return View();
        }
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Create(CombineView combineView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objSaveData.insertData(combineView);
                    TempData["msg"] = "Records Add Successfuly.";
                    return RedirectToAction("Index", "MemberTBs");
                }
                else
                {
                    IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
                    var data = mDta.ToList();
                    IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
                    var tD = tData.ToList();
                    ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
                    ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["msg"] = "Records Add Failed." + ex.Message;
                return RedirectToAction("Payment");
            }
        }
        public ActionResult Transaction(string payment)
        {
            if (payment == "Cash")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "Cash")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else if (payment == "UPI")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "UPI")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else if (payment == "Google Pay")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "Google Pay")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else if (payment == "Phone Pay")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "Phone Pay")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else
            {
                var transactions = db.TransactionTBs
            .Include(t => t.MemberTB).ToList();
                var memberModel = db.MemberTBs.ToList();
                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;
                return View();
            }
        }
        public ActionResult UpdatePayment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionTB transaction = db.TransactionTBs.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }
        [HttpPost]
        public ActionResult UpdateData(int id, int remAmount, int paidAmounts, int dueAmount, DateTime paydate, string mode)
        {
            var existingTransactionTB = db.TransactionTBs.Find(id);
            if (existingTransactionTB == null)
            {
                return HttpNotFound();
            }
            existingTransactionTB.PaidAmount = Convert.ToInt32(paidAmounts + dueAmount);
            existingTransactionTB.DueAmount = Convert.ToInt32(remAmount - dueAmount);
            existingTransactionTB.PaymentDate = paydate;
            existingTransactionTB.PaymentMode = mode;
            db.Entry(existingTransactionTB).Property(x => x.PaidAmount).IsModified = true;
            db.Entry(existingTransactionTB).Property(x => x.DueAmount).IsModified = true;
            db.Entry(existingTransactionTB).Property(x => x.PaymentDate).IsModified = true;
            db.Entry(existingTransactionTB).Property(x => x.PaymentMode).IsModified = true;
            db.SaveChanges();
            return RedirectToAction("Dues");
        }
        public ActionResult UpdateMember(int? id, int? mid)
        {
            IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
            var data = mDta.ToList();
            IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
            var tD = tData.ToList();
            ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
            ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
            var combineData = new CombineView
            {
                member = db.MemberTBs.Find(id),
                transaction = db.TransactionTBs.Find(mid)
            };
            return View(combineData);
        }
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult UpdateMemberData(CombineView combineView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objSaveData.UpdateData(combineView);
                    TempData["msg"] = "Records Add Successfuly.";
                    return RedirectToAction("Index", "MemberTBs");
                }
                else
                {
                    IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
                    var data = mDta.ToList();
                    IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
                    var tD = tData.ToList();
                    ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
                    ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["msg"] = "Records Add Failed." + ex.Message;
                return RedirectToAction("Payment");
            }
        }
        public ActionResult DeleteMember(int? id, int? mid)
        {
            if (id == null && mid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var combineData = new CombineView
            {
                member = db.MemberTBs.Find(id),
                transaction = db.TransactionTBs.Find(mid)
            };
            if (combineData == null)
            {
                return HttpNotFound();
            }
            return View(combineData);
        }
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult DeleteConfirmed(int id, int mid)
        {
            MemberTB memberTB = db.MemberTBs.Find(id);
            TransactionTB transactionTB = db.TransactionTBs.Find(mid);

            db.TransactionTBs.Remove(transactionTB);
            db.MemberTBs.Remove(memberTB);

            db.SaveChanges();
            return RedirectToAction("Index", "MemberTBs");
        }

        public ActionResult ConvertVisitor(int? id)
        {
            CombineView model = new CombineView();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VisitorTB visitor = db.VisitorTBs.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            model.member = new MemberTB();
            model.member.Name = visitor.name;
            model.member.Phone = visitor.phone;
            model.member.Email = visitor.email;
            model.member.DOB = visitor.DOB;
            model.member.Address = visitor.address;
            model.member.Gender = visitor.gender;
            model.member.ID = visitor.ID;
            IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
            var data = mDta.ToList();

Gym Management System/Controllers/VisitorTBsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Gym_Management_System.Models;



namespace Gym_Management_System.Controllers
{
    public class VisitorTBsController : Controller
    {
        private GYMDBEntities4 db = new GYMDBEntities4();

        // GET: VisitorTBs
        public ActionResult Index()
        {
            return View(db.VisitorTBs.ToList());
        }
        [HttpGet]
        public async Task<ActionResult> Index(string search)
        {
            var data = from x in db.VisitorTBs select x;
            if (!String.IsNullOrEmpty(search))
            {
                data = data.Where(x => x.name.Contains(search));
            }
            return View(await data.AsNoTracking().ToListAsync());
        }
        // GET: VisitorTBs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VisitorTB visitorTB = db.VisitorTBs.Find(id);
            if (visitorTB == null)
            {
                return HttpNotFound();
            }
            return View(visitorTB);
        }

        // GET: VisitorTBs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VisitorTBs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,name,phone,email,visitDate,DOB,address,gender,enquiryMode")] VisitorTB visitorTB)
        {
            if (ModelState.IsValid)
            {
                db.VisitorTBs.Add(visitorTB);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(visitorTB);
        }

        // GET: VisitorTBs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VisitorTB visitorTB = db.VisitorTBs.Find(id);
            if (visitorTB == null)
            {
                return HttpNotFound();
            }
            return View(visitorTB);
        }

        // POST: VisitorTBs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,name,phone,email,visitDate,DOB,address,gender,enquiryMode")] VisitorTB visitorTB)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visitorTB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(visitorTB);
        }

        // GET: VisitorTBs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VisitorTB visitorTB = db.VisitorTBs.Find(id);
            if (visitorTB == null)
            {
                return HttpNotFound();
            }
            return View(visitorTB);
        }

        // POST: VisitorTBs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VisitorTB visitorTB = db.VisitorTBs.Find(id);
            db.VisitorTBs.Remove(visitorTB);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gym Management System/Views/VisitorTBs/Create.cshtml
@model Gym_Management_System.Models.VisitorTB

@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
<link href="~/CSS/Style.css" rel="stylesheet" />
<div class="container">
    <h1 class="mt-4">Add Gym Visitor</h1>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @required = "required" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Phone", @required = "required" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @required = "required" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.visitDate, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.visitDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.visitDate, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control", @required = "required", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Addres", @required = "required" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label class="form-label">Gender</label>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.gender, "Male", new { @class = "form-check-input" })
                    <label class="form-check-label" for="male">Male</label>
                </div>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.gender, "Female", new { @class = "form-check-input", @value = "Female" })
                    <label class="form-check-label" for="female">Female</label>
                </div>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.gender, "Other", new { @class = "form-check-input", @value = "Other" })
                    <label class="form-check-label" for="other">Other</label>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label class="form-label">Enquiry Mode</label>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.enquiryMode, "Call", new { @class = "form-check-input", @value = "Call" })
                    <label class="form-check-label" for="call">Call</label>
                </div>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.enquiryMode, "Visit", new { @class = "form-check-input", @value = "Visit" })
                    <label class="form-check-label" for="visit">Visit</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 d-grid gap-2">
            <a href="@Url.Action("Index","VisitorTBs")" class="btn btn-outline-secondary">Cancel</a>
        </div>
        <div class="col-md-6 d-grid gap-2">
            <input type="submit" value="Submit" class="btn btn-outline-success" />
        </div>
    </div>
</div>
}

Gym Management System/Views/VisitorTBs/Details.cshtml
@model Gym_Management_System.Models.VisitorTB

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VisitorTB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.visitDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.visitDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enquiryMode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enquiryMode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Gym Management System/Views/VisitorTBs/Edit.cshtml
@model Gym_Management_System.Models.VisitorTB

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<link href="~/CSS/Style.css" rel="stylesheet" />
<div class="container">
    <h1 class="mt-4">Add Gym Visitor</h1>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @required = "required" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Phone", @required = "required" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @required = "required" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.visitDate, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.visitDate, new { htmlAttributes = new { @class = "form-control",} })
                @Html.ValidationMessageFor(model => model.visitDate, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control", @required = "required",} })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Addres", @required = "required" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label class="form-label">Gender</label>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.gender, "Male", new { @class = "form-check-input" })
                    <label class="form-check-label" for="male">Male</label>
                </div>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.gender, "Female", new { @class = "form-check-input", @value = "Female" })
                    <label class="form-check-label" for="female">Female</label>
                </div>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.gender, "Other", new { @class = "form-check-input", @value = "Other" })
                    <label class="form-check-label" for="other">Other</label>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label class="form-label">Enquiry Mode</label>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.enquiryMode, "Call", new { @class = "form-check-input", @value = "Call" })
                    <label class="form-check-label" for="call">Call</label>
                </div>
                <div class="form-check">
                    @Html.RadioButtonFor(model => model.enquiryMode, "Visit", new { @class = "form-check-input", @value = "Visit" })
                    <label class="form-check-label" for="visit">Visit</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 d-grid gap-2">
            <a href="@Url.Action("Index","VisitorTBs")" class="btn btn-outline-secondary">Cancel</a>
        </div>
        <div class="col-md-6 d-grid gap-2">
            <input type="submit" value="Submit" class="btn btn-outline-success" />
        </div>
    </div>
</div>
}

Gym Management System/Views/VisitorTBs/Index.cshtml
@model IEnumerable<Gym_Management_System.Models.VisitorTB>

@{
    ViewBag.Title = "Index";
}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active" style="margin-left:20px">
                <span class="navbar-brand">Show</span>
            </li>
            <li>
                <span class="navbar-brand">@Model.Count()</span><span>entries</span>
            </li>
        </ul>
        <form method="get" class="form-inline my-2 my-lg-0" style="display: flex; margin-left:15px;">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <button class="btn btn-outline-success my-2 my-sm-0" style="margin-left:10px;" type="submit">Search</button>
        </form>
    </div>
    @*<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-right:50px">Add Visitor</button>*@
    <a href="@Url.Action("Create", "VisitorTBs")" class="btn btn-primary" style="margin-right:50px">Add Visitor</a>
</nav>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col"><label for="name">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name</label></th>
            <th scope="col">Phone</th>
            <th scope="col">Email</th>
            <th scope="col">Visit Date</th>
            <th scope="col">DOB</th>
            <th scope="col">Address</th>
            <th scope="col">Action</th>
            <th scope="col">Convert to Member</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <th scope="row"><img src="~/Icon/profile.jpg" width="30px" height="30px" />&nbsp;&nbsp;@Html.DisplayFor(modelItem => item.name)</th>
            <td> @Html.DisplayFor(modelItem => item.phone)</td>
            <td>@Html.DisplayFor(modelItem => item.email)</td>
            <td>
                @{
                    @(
                            item.visitDate.HasValue
                            ? item.visitDate.Value.ToString("dd-MM-yyyy")
                            : "N/A"
                        )
                }
            </td>
            <td>
                @{
                    @(
                            item.DOB.HasValue
                            ? item.DOB.Value.ToString("dd-MM-yyyy")
                            : "N/A"
                        )
                }
            </td>
        <td>@Html.DisplayFor(modelItem => item.address)</td>
        <td>
            <a id="editLink" href="@Url.Action("Edit", new { id = item.ID })">
                <img id="editImage" src="~/Icon/edit-1-2.svg" alt="Edit" />
            </a>
            <a id="editLink" href="@Url.Action("Delete", new { id = item.ID })">
                <img id="editImage1" src="~/Icon/trash2-2.svg" alt="Edit" />
            </a>
        </td>
        <td>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-primary" onclick="window.location='@Url.Action("ConvertVisitor", "Dashboard", new { id = item.ID })'">Convert</button>
        </td>
        </tr>
        }

    </tbody>
</table>