Gym Management System/Models/MembershipTB.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipTB
    {
        public int ID { get; set; }
        public string MembershipPlan { get; set; }
        public int Price { get; set; }
        public int Days { get; set; }
        public string Type { get; set; }
    }
}

Gym Management System/Controllers/MembershipTBsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Gym_Management_System.Models;

namespace Gym_Management_System.Controllers
{
    public class MembershipTBsController : Controller
    {
        private GYMDBEntities4 db = new GYMDBEntities4();

        // GET: MembershipTBs
        public ActionResult Index()
        {
            return View(db.MembershipTBs.ToList());
        }
        [HttpGet]
        public async Task<ActionResult> Index(string search)
        {
            var data = from x in db.MembershipTBs select x;
            if (!String.IsNullOrEmpty(search))
            {
                data = data.Where(x => x.MembershipPlan.Contains(search));
            }
            return View(await data.AsNoTracking().ToListAsync());
        }
        // GET: MembershipTBs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MembershipTB membershipTB = db.MembershipTBs.Find(id);
            if (membershipTB == null)
            {
                return HttpNotFound();
            }
            return View(membershipTB);
        }
        // GET: MembershipTBs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MembershipTBs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,MembershipPlan,Price,Days,Type")] MembershipTB membershipTB)
        {
            if (ModelState.IsValid)
            {
                db.MembershipTBs.Add(membershipTB);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(membershipTB);
        }

        // GET: MembershipTBs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MembershipTB membershipTB = db.MembershipTBs.Find(id);
            if (membershipTB == null)
            {
                return HttpNotFound();
            }
            return View(membershipTB);
        }

        // POST: MembershipTBs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,MembershipPlan,Price,Days,Type")] MembershipTB membershipTB)
        {
            if (ModelState.IsValid)
            {
                db.Entry(membershipTB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(membershipTB);
        }

        // GET: MembershipTBs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MembershipTB membershipTB = db.MembershipTBs.Find(id);
            if (membershipTB == null)
            {
                return HttpNotFound();
            }
            return View(membershipTB);
        }

        // POST: MembershipTBs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MembershipTB membershipTB = db.MembershipTBs.Find(id);
            db.MembershipTBs.Remove(membershipTB);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gym Management System/Views/MembershipTBs/Create.cshtml
@model Gym_Management_System.Models.MembershipTB

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()
<link href="~/CSS/Style.css" rel="stylesheet" />
<div class="container">
    <h1 class="mt-4">Add Gym Membership Plan</h1>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.MembershipPlan, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.MembershipPlan, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Membership Name", @required = "required" } })
                @Html.ValidationMessageFor(model => model.MembershipPlan, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Price", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Days, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Days, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Days", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Type", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 d-grid gap-2">
            <a href="@Url.Action("Index","MembershipTBs")" class="btn btn-outline-secondary">Cancel</a>
        </div>
        <div class="col-md-6 d-grid gap-2">
            <input type="submit" value="Submit" class="btn btn-outline-success" />
        </div>
    </div>
</div>
}

Gym Management System/Views/MembershipTBs/Delete.cshtml
@model Gym_Management_System.Models.MembershipTB

@{
    ViewBag.Title = "Delete";
}

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 600px;
        margin: 50px auto;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 40px;
    }

    h2 {
        font-size: 28px;
        color: #333;
        text-align: center;
        margin-bottom: 20px;
    }

    h3 {
        font-size: 22px;
        color: #555;
        text-align: center;
        margin-bottom: 30px;
    }

    h4 {
        font-size: 18px;
        color: #333;
        margin-bottom: 20px;
    }

    .dl-horizontal dt {
        font-weight: bold;
        margin-bottom: 10px;
    }

    .dl-horizontal dd {
        margin-bottom: 20px;
    }

    .btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    .btn-submit {
        background-color: #4CAF50;
        color: white;
    }

        .btn-submit:hover {
            background-color: #45a049;
        }

    .btn-cancel {
        background-color: #ccc;
        color: #333;
    }

        .btn-cancel:hover {
            background-color: #bbb;
        }
</style>
<div class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4> Delete MemberTB</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MembershipPlan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MembershipPlan)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Days)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Days)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Gym Management System/Views/MembershipTBs/Details.cshtml
@model Gym_Management_System.Models.MembershipTB

@{
    ViewBag.Title = "Details";
}
<link href="~/CSS/DeleteStyle.css" rel="stylesheet" />
<h2>Details</h2>

<div>
    <h4>MembershipTB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MembershipPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MembershipPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Days)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Days)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Gym Management System/Views/MembershipTBs/Edit.cshtml
@model Gym_Management_System.Models.MembershipTB

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <link href="~/CSS/Style.css" rel="stylesheet" />
    <div class="container">
        <h1 class="mt-4">Add Gym Visitor</h1>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.MembershipPlan, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.MembershipPlan, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Membership Name", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.MembershipPlan, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Price", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Days, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Days, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Days", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Type", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 d-grid gap-2">
                <a href="@Url.Action("Index","MembershipTBs")" class="btn btn-outline-secondary">Cancel</a>
            </div>
            <div class="col-md-6 d-grid gap-2">
                <input type="submit" value="Submit" class="btn btn-outline-success" />
            </div>
        </div>
    </div>
}

Gym Management System/Views/MembershipTBs/Index.cshtml
@model IEnumerable<Gym_Management_System.Models.MembershipTB>

@{
    ViewBag.Title = "Index";
}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active" style="margin-left:20px">
                <span class="navbar-brand">Show</span>
            </li>
            <li>
                <span class="navbar-brand">@Model.Count()</span><span>entries</span>
            </li>
        </ul>
        <form method="get" class="form-inline my-2 my-lg-0" style="display: flex; margin-left:15px;">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <button class="btn btn-outline-success my-2 my-sm-0" style="margin-left:10px;" type="submit">Search</button>
        </form>
    </div>
    <a href="@Url.Action("Create", "MembershipTBs")" class="btn btn-primary" style="margin-right:50px">Add Plan</a>
</nav>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col"><label for="name">Membership Plan</label></th>
            <th scope="col">Price</th>
            <th scope="col">Days</th>
            <th scope="col">Type</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@Html.DisplayFor(modelItem => item.MembershipPlan)</th>
                <td> @Html.DisplayFor(modelItem => item.Price) Rs</td>
                <td>@Html.DisplayFor(modelItem => item.Days) Days</td>
                <td>@Html.DisplayFor(modelItem => item.Type)</td>
                <td>
                    <a id="editLink" href="@Url.Action("Edit", new { id = item.ID })">
                        <img id="editImage" src="~/Icon/edit-1-2.svg" alt="Edit" />
                    </a>
                    <a id="editLink" href="@Url.Action("Delete", new { id = item.ID })">
                        <img id="editImage1" src="~/Icon/trash2-2.svg" alt="Edit" />
                    </a>
                </td>
            </tr>
        }

    </tbody>
</table>