Gym Management System/Controllers/DashboardController.cs
using Gym_Management_System.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Gym_Management_System.Controllers
{
    public class DashboardController : Controller
    {
        private SaveData objSaveData;
        private GYMDBEntities4 db = new GYMDBEntities4();
        public DashboardController()
        {
            objSaveData = new SaveData();
        }
        // GET: Dashboad
        public ActionResult Dues()
        {
            var transactions = db.TransactionTBs
    .Where(t => t.DueAmount != null && t.DueAmount != 0)
    .Include(t => t.MemberTB)
    .ToList();
            var memberModel = db.MemberTBs.ToList();
            ViewBag.Transactions = transactions;
            ViewBag.Members = memberModel;
            return View();
        }
        public ActionResult Payment()
        {
            IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
            var data = mDta.ToList();
            IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
            var tD = tData.ToList();
            ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
            ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
            return View();
        }
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Create(CombineView combineView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objSaveData.insertData(combineView);
                    TempData["msg"] = "Records Add Successfuly.";
                    return RedirectToAction("Index", "MemberTBs");
                }
                else
                {
                    IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
                    var data = mDta.ToList();
                    IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
                    var tD = tData.ToList();
                    ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
                    ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["msg"] = "Records Add Failed." + ex.Message;
                return RedirectToAction("Payment");
            }
        }
        public ActionResult Transaction(string payment)
        {
            if (payment == "Cash")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "Cash")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else if (payment == "UPI")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "UPI")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else if (payment == "Google Pay")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "Google Pay")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else if (payment == "Phone Pay")
            {
                var transactions = db.TransactionTBs
                     .Include(t => t.MemberTB)
                     .Where(t => t.PaymentMode == "Phone Pay")
                     .ToList();

                var memberModel = db.MemberTBs.ToList();

                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;

                return View();
            }
            else
            {
                var transactions = db.TransactionTBs
            .Include(t => t.MemberTB).ToList();
                var memberModel = db.MemberTBs.ToList();
                ViewBag.Transactions = transactions;
                ViewBag.Members = memberModel;
                return View();
            }
        }
        public ActionResult UpdatePayment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionTB transaction = db.TransactionTBs.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }
        [HttpPost]
        public ActionResult UpdateData(int id, int remAmount, int paidAmounts, int dueAmount, DateTime paydate, string mode)
        {
            var existingTransactionTB = db.TransactionTBs.Find(id);
            if (existingTransactionTB == null)
            {
                return HttpNotFound();
            }
            existingTransactionTB.PaidAmount = Convert.ToInt32(paidAmounts + dueAmount);
            existingTransactionTB.DueAmount = Convert.ToInt32(remAmount - dueAmount);
            existingTransactionTB.PaymentDate = paydate;
            existingTransactionTB.PaymentMode = mode;
            db.Entry(existingTransactionTB).Property(x => x.PaidAmount).IsModified = true;
            db.Entry(existingTransactionTB).Property(x => x.DueAmount).IsModified = true;
            db.Entry(existingTransactionTB).Property(x => x.PaymentDate).IsModified = true;
            db.Entry(existingTransactionTB).Property(x => x.PaymentMode).IsModified = true;
            db.SaveChanges();
            return RedirectToAction("Dues");
        }
        public ActionResult UpdateMember(int? id, int? mid)
        {
            IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
            var data = mDta.ToList();
            IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
            var tD = tData.ToList();
            ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
            ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
            var combineData = new CombineView
            {
                member = db.MemberTBs.Find(id),
                transaction = db.TransactionTBs.Find(mid)
            };
            return View(combineData);
        }
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult UpdateMemberData(CombineView combineView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objSaveData.UpdateData(combineView);
                    TempData["msg"] = "Records Add Successfuly.";
                    return RedirectToAction("Index", "MemberTBs");
                }
                else
                {
                    IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
                    var data = mDta.ToList();
                    IEnumerable<TrainerTB> tData = db.TrainerTBs.ToList();
                    var tD = tData.ToList();
                    ViewBag.trainerSelect = new SelectList(tD, "Name", "Name");
                    ViewBag.MembershipPlans = new SelectList(data, "MembershipPlan", "MembershipPlan");
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["msg"] = "Records Add Failed." + ex.Message;
                return RedirectToAction("Payment");
            }
        }
        public ActionResult DeleteMember(int? id, int? mid)
        {
            if (id == null && mid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var combineData = new CombineView
            {
                member = db.MemberTBs.Find(id),
                transaction = db.TransactionTBs.Find(mid)
            };
            if (combineData == null)
            {
                return HttpNotFound();
            }
            return View(combineData);
        }
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult DeleteConfirmed(int id, int mid)
        {
            MemberTB memberTB = db.MemberTBs.Find(id);
            TransactionTB transactionTB = db.TransactionTBs.Find(mid);

            db.TransactionTBs.Remove(transactionTB);
            db.MemberTBs.Remove(memberTB);

            db.SaveChanges();
            return RedirectToAction("Index", "MemberTBs");
        }

        public ActionResult ConvertVisitor(int? id)
        {
            CombineView model = new CombineView();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VisitorTB visitor = db.VisitorTBs.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            model.member = new MemberTB();
            model.member.Name = visitor.name;
            model.member.Phone = visitor.phone;
            model.member.Email = visitor.email;
            model.member.DOB = visitor.DOB;
            model.member.Address = visitor.address;
            model.member.Gender = visitor.gender;
            model.member.ID = visitor.ID;
            IEnumerable<MembershipTB> mDta = db.MembershipTBs.ToList();
            var data = mDta.ToList();

Gym Management System/Controllers/TrainerTBsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Gym_Management_System.Models;

namespace Gym_Management_System.Controllers
{
    public class TrainerTBsController : Controller
    {
        private GYMDBEntities4 db = new GYMDBEntities4();

        // GET: TrainerTBs
        public ActionResult Index()
        {
            return View(db.TrainerTBs.ToList());
        }
        [HttpGet]
        public async Task<ActionResult> Index(string search)
        {
            var data = from x in db.TrainerTBs select x;
            if (!String.IsNullOrEmpty(search))
            {
                data = data.Where(x => x.Name.Contains(search));
            }
            return View(await data.AsNoTracking().ToListAsync());
        }
        // GET: TrainerTBs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainerTB trainerTB = db.TrainerTBs.Find(id);
            if (trainerTB == null)
            {
                return HttpNotFound();
            }
            return View(trainerTB);
        }

        // GET: TrainerTBs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TrainerTBs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Phone,Email,JoinDate,DOB,Address,Experience")] TrainerTB trainerTB)
        {
            if (ModelState.IsValid)
            {
                db.TrainerTBs.Add(trainerTB);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trainerTB);
        }

        // GET: TrainerTBs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainerTB trainerTB = db.TrainerTBs.Find(id);
            if (trainerTB == null)
            {
                return HttpNotFound();
            }
            return View(trainerTB);
        }

        // POST: TrainerTBs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Phone,Email,JoinDate,DOB,Address,Experience")] TrainerTB trainerTB)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainerTB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trainerTB);
        }

        // GET: TrainerTBs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainerTB trainerTB = db.TrainerTBs.Find(id);
            if (trainerTB == null)
            {
                return HttpNotFound();
            }
            return View(trainerTB);
        }

        // POST: TrainerTBs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TrainerTB trainerTB = db.TrainerTBs.Find(id);
            db.TrainerTBs.Remove(trainerTB);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gym Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProFit GYM</title>
    <!-- CSS -->
    <!-- Boxicons CSS -->
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
          rel="stylesheet" />
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.4.0/font/bootstrap-icons.min.css ">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        /* Google Fonts - Poppins */
  @*@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap");*@

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins", sans-serif;
}
body {
  min-height: 100%;
  background: #e3f2fd;
}
nav {
  position: fixed;
  top: 0;
  left: 0;
  height: 70px;
  width: 100%;
  display: flex;
  align-items: center;
  background: #fff;
  box-shadow: 0 0 1px rgba(0, 0, 0, 0.1);
}
nav .logo {
  display: flex;
  align-items: center;
  margin: 0 24px;
}
.logo .menu-icon {
  color: #333;
  font-size: 24px;
  margin-right: 14px;
  cursor: pointer;
}
.logo .logo-name {
  color: #333;
  font-size: 22px;
  font-weight: 500;
}
nav .sidebar {
  position: fixed;
  top: 0;
  height: 100%;
  width: 260px;
  padding: 20px 0;
  background-color: #fff;
  box-shadow: 0 5px 1px rgba(0, 0, 0, 0.1);
  transition: all 0.4s ease;
}
nav.open .sidebar {
  left: 0;
}
.sidebar .sidebar-content {
  display: flex;
  height: 100%;
  flex-direction: column;
  justify-content: space-between;
  padding: 30px 16px;
}
.sidebar-content .list {
  list-style: none;
}
.list .nav-link {
  display: flex;
  align-items: center;
  margin: 8px 0;
   padding: 14px 12px;
  border-radius: 8px;
  text-decoration: none;
}
.lists .nav-link:hover {
  background-color: #979797;
}
.nav-link .icon {
  margin-right: 14px;
  font-size: 20px;
  color: #707070;
}
.nav-link .link {
  font-size: 16px;
  color: #707070;
  font-weight: 400;
}
.lists .nav-link:hover .icon,
.lists .nav-link:hover .link {
  color: #fff;
}
.section {
    margin-top:100px;
    margin-left:248px;
}
        .custom-modal-content {
            max-width: 90%;
        }
    </style>
</head>
<body>
    <nav>
        <div class="logo">
            <i class="bx bx-menu menu-icon"></i>
            <span class="logo-name">ProFit Gym</span>
        </div>
        <div class="sidebar">
            <div class="logo">
                <i class="bx bx-menu menu-icon"></i>
                <span class="logo-name">ProFit Gym</span>
            </div>
            <div class="sidebar-content">
                <ul class="lists">
                    <li class="list">
                        <a href="@Url.Action("Index", "Home")" class="nav-link"><i class="bx bx-home-alt icon"></i>Dashboard</a>
                    </li>
                    <li class="list">
                        <a href="@Url.Action("Index", "VisitorTBs")" class="nav-link"><i class="bx bx-bar-chart-alt-2 icon"></i>Visitor</a>
                    </li>
                    <li class="list">
                        <a href="@Url.Action("Index", "MemberTbs")" class="nav-link"><i class="bx bx-bell icon"></i>Members</a>
                    </li>
                    <li class="list">
                        <a href="@Url.Action("Index", "TrainerTBs")" class="nav-link"><i class="bx bx-bell icon"></i>Trainer</a>
                    </li>
                    <li class="list">
                        <a href="@Url.Action("Dues", "Dashboard")" class="nav-link"><i class="bx bx-bell icon"></i>Dues</a>
                    </li>
                    @if (Session["UserRole"] != null && Session["UserRole"].ToString() == "Admin")
                    {
                <li class="list">
                    <a href="@Url.Action("Transaction", "Dashboard")" class="nav-link"><i class="bx bx-bell icon"></i>Transaction</a>
                </li>}
                    <li class="list">
                        <a href="@Url.Action("Index", "MembershipTBs")" class="nav-link"><i class="bx bx-folder-open icon"></i>Membership</a>
                    </li>
                    <li class="list">
                        <a href="@Url.Action("MembershipEnd", "Home")" class="nav-link"><i class="bx bx-folder-open icon"></i>Membership End</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="section" style="margin-left: 280px">
        @RenderBody()
    </section>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>